/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.action;

import controller.FactoryDAO;
import controller.dao.interfaces.IGenerticDAO;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableModel;
import model.Category;
import model.Order;
import model.OrderDetails;
import model.Product;
import view.DashBoard;
import view.ErrorsMessageDialog;

/**
 *
 * @author THUY
 */
public class CreateOrdering extends javax.swing.JFrame {

    private IGenerticDAO catDAO = FactoryDAO.getData("category");
    private IGenerticDAO proDAO = FactoryDAO.getData("product");
    private IGenerticDAO orderDAO = FactoryDAO.getData("order");

    private List<Category> listCategory;
    private List<Category> listCategoryFood;
    private List<Category> listCategoryDrink;

    private List<Product> listFoods;
    private List<Product> listDrinks;
    private List<Product> listProductFoods;
    private List<Product> listProductDrinks;

    private List<Order> listOrder;
    private List<OrderDetails> listOrderDetails;

    private DefaultTableModel modelMenuDrink;
    private DefaultTableModel modelMenuFood;
    private DefaultTableModel modelOrder;

    private int orderID = 0;

    Locale localeVN = new Locale("vi", "VN");
    NumberFormat vn = NumberFormat.getInstance(localeVN);

    /**
     * Creates new form CreateOrdering
     */
    public CreateOrdering() {
        initComponents();
        this.setLocationRelativeTo(null);

        listCategory = catDAO.getList();
        listCategoryDrink = catDAO.getListDrinks();
        listCategoryFood = catDAO.getListFoods();

        listProductDrinks = proDAO.getListDrinks();
        listProductFoods = proDAO.getListFoods();
        listOrder = orderDAO.getList();

        listOrderDetails = new ArrayList<>();

        modelMenuDrink = (DefaultTableModel) tblMenuDrinks.getModel();
        modelMenuFood = (DefaultTableModel) tblMenuFoods.getModel();
        modelOrder = (DefaultTableModel) tblCurrentOrder.getModel();

        setDataTableMenu(modelMenuFood, listProductFoods);
        setDataTableMenu(modelMenuDrink, listProductDrinks);

        setComboxCategory(comboxFoods, catDAO.getListFoods());
        setComboxCategory(comboxDrinks, catDAO.getListDrinks());

        customTableView(tblMenuFoods);
        customTableView(tblMenuDrinks);
        customTableView(tblCurrentOrder);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bntClearAll = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCurrentOrder = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        bntClearOne = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnFoods = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnDrinks = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblSeparatorFoods = new javax.swing.JLabel();
        lblSeparatorDrinks = new javax.swing.JLabel();
        pnlMainContent = new javax.swing.JPanel();
        panelFoods = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboxFoods = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenuFoods = new javax.swing.JTable();
        btnAddFoods = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelDrinks = new javax.swing.JPanel();
        btnAddDrink = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMenuDrinks = new javax.swing.JTable();
        comboxDrinks = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(98, 66, 43));
        jLabel1.setText("Team ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(204, 204, 255)));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(98, 66, 43));
        jLabel4.setText("Current Order");

        bntClearAll.setBackground(new java.awt.Color(251, 236, 238));
        bntClearAll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 85, 117)));
        bntClearAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntClearAll.setPreferredSize(new java.awt.Dimension(95, 33));
        bntClearAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntClearAllMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(237, 85, 117));
        jLabel9.setText("Clear All");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 33));

        javax.swing.GroupLayout bntClearAllLayout = new javax.swing.GroupLayout(bntClearAll);
        bntClearAll.setLayout(bntClearAllLayout);
        bntClearAllLayout.setHorizontalGroup(
            bntClearAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bntClearAllLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bntClearAllLayout.setVerticalGroup(
            bntClearAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bntClearAllLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBorder(null);

        tblCurrentOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Image", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCurrentOrder.setSelectionBackground(new java.awt.Color(191, 146, 114));
        jScrollPane3.setViewportView(tblCurrentOrder);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 23)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(98, 66, 43));
        jLabel7.setText("Subtotal:");

        txtSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSubtotal.setForeground(new java.awt.Color(145, 82, 47));
        txtSubtotal.setText("0 VNĐ");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel17.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(237, 40, 82));
        jLabel17.setText("Total:");

        jLabel18.setFont(new java.awt.Font("Courier New", 1, 23)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(237, 40, 82));
        jLabel18.setText("total");

        btnCheckout.setBackground(new java.awt.Color(232, 180, 128));
        btnCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Checkout");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_bill_30px.png"))); // NOI18N

        javax.swing.GroupLayout btnCheckoutLayout = new javax.swing.GroupLayout(btnCheckout);
        btnCheckout.setLayout(btnCheckoutLayout);
        btnCheckoutLayout.setHorizontalGroup(
            btnCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCheckoutLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnCheckoutLayout.setVerticalGroup(
            btnCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                        .addComponent(jLabel18))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSubtotal)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        bntClearOne.setBackground(new java.awt.Color(251, 236, 238));
        bntClearOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 85, 117)));
        bntClearOne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntClearOne.setPreferredSize(new java.awt.Dimension(98, 33));
        bntClearOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntClearOneMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(237, 85, 117));
        jLabel11.setText("Clear One");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 33));

        javax.swing.GroupLayout bntClearOneLayout = new javax.swing.GroupLayout(bntClearOne);
        bntClearOne.setLayout(bntClearOneLayout);
        bntClearOneLayout.setHorizontalGroup(
            bntClearOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bntClearOneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        bntClearOneLayout.setVerticalGroup(
            bntClearOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bntClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntClearOne, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bntClearOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(98, 66, 43));

        btnFoods.setBackground(new java.awt.Color(255, 255, 255));
        btnFoods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFoodsMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(145, 82, 47));
        jLabel2.setText("FOODs");

        javax.swing.GroupLayout btnFoodsLayout = new javax.swing.GroupLayout(btnFoods);
        btnFoods.setLayout(btnFoodsLayout);
        btnFoodsLayout.setHorizontalGroup(
            btnFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnFoodsLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(41, 41, 41))
        );
        btnFoodsLayout.setVerticalGroup(
            btnFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFoodsLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnDrinks.setBackground(new java.awt.Color(255, 255, 255));
        btnDrinks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDrinksMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(145, 82, 47));
        jLabel3.setText("DRINKs");

        javax.swing.GroupLayout btnDrinksLayout = new javax.swing.GroupLayout(btnDrinks);
        btnDrinks.setLayout(btnDrinksLayout);
        btnDrinksLayout.setHorizontalGroup(
            btnDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDrinksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(41, 41, 41))
        );
        btnDrinksLayout.setVerticalGroup(
            btnDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        lblSeparatorFoods.setBackground(new java.awt.Color(201, 132, 105));
        lblSeparatorFoods.setText("     ");
        lblSeparatorFoods.setToolTipText("");
        lblSeparatorFoods.setOpaque(true);

        lblSeparatorDrinks.setBackground(new java.awt.Color(255, 255, 255));
        lblSeparatorDrinks.setText("     ");
        lblSeparatorDrinks.setToolTipText("");
        lblSeparatorDrinks.setOpaque(true);

        pnlMainContent.setLayout(new java.awt.CardLayout());

        panelFoods.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(165, 134, 97));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(165, 134, 97));
        jLabel5.setText("Choose category");

        comboxFoods.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        comboxFoods.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Menu" }));
        comboxFoods.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboxFoodsItemStateChanged(evt);
            }
        });

        tblMenuFoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Image", "Price"
            }
        ));
        tblMenuFoods.setSelectionBackground(new java.awt.Color(191, 146, 114));
        jScrollPane1.setViewportView(tblMenuFoods);

        btnAddFoods.setBackground(new java.awt.Color(191, 146, 114));
        btnAddFoods.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnAddFoods.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddFoods.setPreferredSize(new java.awt.Dimension(153, 44));
        btnAddFoods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddFoodsMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_30px_1.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Add to bill");

        javax.swing.GroupLayout btnAddFoodsLayout = new javax.swing.GroupLayout(btnAddFoods);
        btnAddFoods.setLayout(btnAddFoodsLayout);
        btnAddFoodsLayout.setHorizontalGroup(
            btnAddFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAddFoodsLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(31, 31, 31))
        );
        btnAddFoodsLayout.setVerticalGroup(
            btnAddFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFoodsLayout = new javax.swing.GroupLayout(panelFoods);
        panelFoods.setLayout(panelFoodsLayout);
        panelFoodsLayout.setHorizontalGroup(
            panelFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFoodsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFoodsLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                        .addComponent(comboxFoods, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFoodsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddFoods, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFoodsLayout.setVerticalGroup(
            panelFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFoodsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxFoods, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnAddFoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        pnlMainContent.add(panelFoods, "card3");

        panelDrinks.setBackground(new java.awt.Color(255, 255, 255));

        btnAddDrink.setBackground(new java.awt.Color(191, 146, 114));
        btnAddDrink.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnAddDrink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddDrink.setPreferredSize(new java.awt.Dimension(153, 44));
        btnAddDrink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddDrinkMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_30px_1.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("Add to bill");

        javax.swing.GroupLayout btnAddDrinkLayout = new javax.swing.GroupLayout(btnAddDrink);
        btnAddDrink.setLayout(btnAddDrinkLayout);
        btnAddDrinkLayout.setHorizontalGroup(
            btnAddDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAddDrinkLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(31, 31, 31))
        );
        btnAddDrinkLayout.setVerticalGroup(
            btnAddDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        tblMenuDrinks.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblMenuDrinks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Image", "Price"
            }
        ));
        tblMenuDrinks.setSelectionBackground(new java.awt.Color(191, 146, 114));
        jScrollPane2.setViewportView(tblMenuDrinks);

        comboxDrinks.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        comboxDrinks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Menu" }));
        comboxDrinks.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboxDrinksItemStateChanged(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(165, 134, 97));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(165, 134, 97));
        jLabel19.setText("Choose category");

        javax.swing.GroupLayout panelDrinksLayout = new javax.swing.GroupLayout(panelDrinks);
        panelDrinks.setLayout(panelDrinksLayout);
        panelDrinksLayout.setHorizontalGroup(
            panelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDrinksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDrinksLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                        .addComponent(comboxDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDrinksLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDrinksLayout.setVerticalGroup(
            panelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDrinksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnAddDrink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );

        pnlMainContent.add(panelDrinks, "card2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSeparatorFoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFoods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeparatorDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeparatorFoods, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeparatorDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customTableView(JTable tableName) {
        tableName.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tableName.getTableHeader().setOpaque(false);
        tableName.getTableHeader().setBackground(new Color(32, 136, 203));
        tableName.getTableHeader().setForeground(new Color(255, 255, 255));
        tableName.setRowHeight(25);
        tableName.setFont(new Font("Segoe UI", Font.PLAIN, 15));
    }

    private void setOrderId() {
        listOrder = orderDAO.getList();
        if (listOrder.size() == 0) {
            orderID = 100000;
        } else {
            orderID = listOrder.get(listOrder.size() - 1).getId() + 1;
        }
    }

    private void setComboxCategory(JComboBox comboxName, List<Category> list) {
        for (Category p : list) {
            comboxName.addItem(p.getName());
        }
    }

    private void setDataTableMenu(DefaultTableModel modelname, List<Product> list) {
        modelname.setRowCount(0);
        for (Product p : list) {
            modelname.addRow(new Object[]{
                p.getName(), p.getImage(), vn.format(p.getSale_price())
            });
        }
    }

    private void btnFoodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFoodsMouseClicked
        lblSeparatorFoods.setBackground(new Color(201, 132, 105));
        lblSeparatorDrinks.setBackground(Color.WHITE);

        pnlMainContent.removeAll();
        pnlMainContent.add(panelFoods);
        pnlMainContent.repaint();
        pnlMainContent.revalidate();

    }//GEN-LAST:event_btnFoodsMouseClicked

    private void btnDrinksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrinksMouseClicked
        lblSeparatorFoods.setBackground(Color.WHITE);
        lblSeparatorDrinks.setBackground(new Color(201, 132, 105));

        pnlMainContent.removeAll();
        pnlMainContent.add(panelDrinks);
        pnlMainContent.repaint();
        pnlMainContent.revalidate();
    }//GEN-LAST:event_btnDrinksMouseClicked

    private void btnAddDrinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddDrinkMouseClicked
        // add product to the bill

        int indexselected = tblMenuDrinks.getSelectedRow();

        if (indexselected == -1) {
            new ErrorsMessageDialog().setMessage("Please choose food!");
        } else {
            // check list order (procduct is exist?)    
            int count = 0;
            int i = 0;
            int updateQty = 0;
            int currentQty = 0;

            Product p = listProductDrinks.get(indexselected);
            String proID = p.getId();
            String proName = p.getName();
            String image = p.getImage();
            float price = p.getSale_price();

            setOrderId();         
            OrderDetails od = new OrderDetails();
            od.setOrder_id(orderID);
            od.setPro_id(proID);
            od.setPro_name(proName);
            od.setQuantity(1);
            od.setPrice(price);

            for (OrderDetails o : listOrderDetails) {
                if (o.getPro_id().equals(proID)) {
                    currentQty = Integer.parseInt(tblCurrentOrder.getModel().getValueAt(i, 2).toString());
                    updateQty = currentQty + 1;
                    od.setQuantity(updateQty);
                    listOrderDetails.remove(i);
                    listOrderDetails.add(od);
                    count++;
                }
                i++;
            }

            if (count != 1) {
                listOrderDetails.add(od);
            }

            showListOrder(listOrderDetails);
            calculateTotalBill();
        }
    }//GEN-LAST:event_btnAddDrinkMouseClicked

    private void btnAddFoodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddFoodsMouseClicked
        // add product to the bill

        int indexselected = tblMenuFoods.getSelectedRow();

        if (indexselected == -1) {
            new ErrorsMessageDialog().setMessage("Please choose food!");
        } else {
            // check list order (procduct is exist?)    
            int count = 0;
            int i = 0;
            int updateQty = 0;
            int currentQty = 0;

            Product p = listProductFoods.get(indexselected);
            String proID = p.getId();
            String proName = p.getName();
            String image = p.getImage();
            float price = p.getSale_price();

            setOrderId();
            OrderDetails od = new OrderDetails();
            od.setOrder_id(orderID);
            od.setPro_id(proID);
            od.setPro_name(proName);
            od.setQuantity(1);
            od.setPrice(price);

            for (OrderDetails o : listOrderDetails) {
                if (o.getPro_id().equals(proID)) {
                    currentQty = Integer.parseInt(tblCurrentOrder.getModel().getValueAt(i, 2).toString());
                    updateQty = currentQty + 1;
                    od.setQuantity(updateQty);
                    listOrderDetails.remove(i);
                    listOrderDetails.add(od);
                    count++;
                }
                i++;
            }

            if (count != 1) {
                listOrderDetails.add(od);
            }

            showListOrder(listOrderDetails);
            calculateTotalBill();
        }
    }//GEN-LAST:event_btnAddFoodsMouseClicked

    private void calculateTotalBill() {
        float subtotal = 0;
        for (OrderDetails o : listOrderDetails) {
            subtotal += o.getPrice() * o.getQuantity();
        }

        txtSubtotal.setText(vn.format(subtotal) + " VNĐ");
    }

    private void showListOrder(List<OrderDetails> listOrderDetails) {
        List<Product> listProduct = proDAO.getList();
        modelOrder.setRowCount(0);
        for (OrderDetails o : listOrderDetails) {
            for (Product p : listProduct) {
                if (o.getPro_id().equals(p.getId())) {
                    modelOrder.addRow(new Object[]{
                        o.getPro_name(), p.getImage(), o.getQuantity(), vn.format(o.getPrice())
                    });
                }
            }
        }
    }

    private void comboxFoodsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboxFoodsItemStateChanged

        if (evt.getStateChange() == evt.SELECTED) {
            if (comboxFoods.getSelectedItem().toString().equals("All Menu")) {
                listProductFoods = proDAO.getListFoods();
                setDataTableMenu(modelMenuFood, listProductFoods);
            } else {
                listCategoryFood = catDAO.getListFoods();
                int indexSelected = comboxFoods.getSelectedIndex();
                int cat_id = listCategoryFood.get(indexSelected - 1).getId();

                listProductFoods.clear();
                listFoods = proDAO.getListFoods();
                for (Product p : listFoods) {
                    if (p.getCat_id() == cat_id) {
                        listProductFoods.add(p);
                    }
                }
                setDataTableMenu(modelMenuFood, listProductFoods);
            }
        }

    }//GEN-LAST:event_comboxFoodsItemStateChanged

    private void comboxDrinksItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboxDrinksItemStateChanged

        if (evt.getStateChange() == evt.SELECTED) {
            if (comboxDrinks.getSelectedItem().toString().equals("All Menu")) {
                listProductDrinks = proDAO.getListDrinks();
                setDataTableMenu(modelMenuDrink, listProductDrinks);
            } else {
                listCategoryFood = catDAO.getListDrinks();

                int indexSelected = comboxDrinks.getSelectedIndex();
                int cat_id = listCategoryDrink.get(indexSelected - 1).getId();

                listProductDrinks.clear();
                listDrinks = proDAO.getListDrinks();
                for (Product p : listDrinks) {
                    if (p.getCat_id() == cat_id) {
                        listProductDrinks.add(p);
                    }
                }
                setDataTableMenu(modelMenuDrink, listProductDrinks);
            }
        }
    }//GEN-LAST:event_comboxDrinksItemStateChanged

    private void bntClearOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntClearOneMouseClicked
        int indexSelected = tblCurrentOrder.getSelectedRow();
        if (indexSelected == -1) {
            new ErrorsMessageDialog().setMessage("Please choose product to delete!");
        } else {
            listOrderDetails.remove(indexSelected);
            showListOrder(listOrderDetails);
            calculateTotalBill();
        }
    }//GEN-LAST:event_bntClearOneMouseClicked

    private void bntClearAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntClearAllMouseClicked
        listOrderDetails.clear();
        showListOrder(listOrderDetails);
        calculateTotalBill();
    }//GEN-LAST:event_bntClearAllMouseClicked

    private void btnCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseClicked
        if (listOrderDetails.size() == 0) {
            new ErrorsMessageDialog().setMessage("Order list is empty!");
        } else {
            // set data
            ViewBill bill = new ViewBill(this, rootPaneCheckingEnabled);
            setOrderId();
            bill.setData(orderID, listOrderDetails);
            bill.setVisible(true);
        }
    }//GEN-LAST:event_btnCheckoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    ex.printStackTrace();
                } catch (InstantiationException ex) {
                    ex.printStackTrace();
                } catch (IllegalAccessException ex) {
                    ex.printStackTrace();
                } catch (UnsupportedLookAndFeelException ex) {
                    ex.printStackTrace();
                }
                new CreateOrdering().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bntClearAll;
    private javax.swing.JPanel bntClearOne;
    private javax.swing.JPanel btnAddDrink;
    private javax.swing.JPanel btnAddFoods;
    private javax.swing.JPanel btnCheckout;
    private javax.swing.JPanel btnDrinks;
    private javax.swing.JPanel btnFoods;
    private javax.swing.JComboBox<String> comboxDrinks;
    private javax.swing.JComboBox<String> comboxFoods;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSeparatorDrinks;
    private javax.swing.JLabel lblSeparatorFoods;
    private javax.swing.JPanel panelDrinks;
    private javax.swing.JPanel panelFoods;
    private javax.swing.JPanel pnlMainContent;
    private javax.swing.JTable tblCurrentOrder;
    private javax.swing.JTable tblMenuDrinks;
    private javax.swing.JTable tblMenuFoods;
    private javax.swing.JLabel txtSubtotal;
    // End of variables declaration//GEN-END:variables
}
